apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: my-app
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: metrics
      protocol: TCP
      port: 9095
      targetPort: 9095

